Task23_Low/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Task23_Low.Controllers
{
    public class ArticlesController : Controller
    {
        // GET: Articles
        public ActionResult Index()
        {
            return View();
        }
    }
}

Task23_Low/Controllers/CommentaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Task23_Low.Controllers
{
    public class CommentaryController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }
    }
}

Task23_Low/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Task23_Low.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Task23_Low/Controllers/QuestionnaireController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Task23_Low.Controllers
{
    public class QuestionnaireController : Controller
    {
        private List<Dictionary<string, string>> _questionnaries = new List<Dictionary<string, string>>();
        // GET: Questionnaire
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Result()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Result")]
        public ActionResult ResultPost()
        {
            return View();
        }
    }
}

Task23_Low/Views/Articles/Index.cshtml
@{
    ViewBag.Title = "Articles";
}
<div id="first_article">
    <h1>Неожиданности Хмельницкого: "ратуша" оказалась башней пожарного депо, а сам город — кофейной столицей </h1>
    <h2>08.04.2021</h2>
    <h3>Знаменитый рынок, кафе на каждом шагу и остров любви
    — чем привлекает гостей город Хмельницкий.</h3>
    <p>
        В Хмельницком, как и в большинстве украинских городов есть своя ратуша.
        Но эту башню так называют только туристы, а местные жители знают, что это — элемент пожарного депо, построенного в середине 1950-х годов.
        О том, какими еще неожиданностями удивляет город своих гостей, говорится в сюжете ТСН.19: 30.
        Как и во всех городах, в которых в рамках проекта "30 лет Независимости" уже побывала съемочная группа ТСН, в Хмельницком много приветливых людей.
        Улыбками здесь встречают везде.
        А майор в отставке и экскурсовод Игорь Байдак, который знакомил с городом,
        оказался еще и первый "поэтическим гидом", который о Хмельницком может рассказывать и в стихах, и в прозе.
        В городе также много детей — веселых, активных и спортивных. Для них здесь все — развлекательные площадки, велодорожки.
        Есть в городе и кукольный театр, и детский кинотеатр, и экспонаты, которыми можно управлять.
        В Хмельницком более 700 кофеен на 270 тысяч населения. Поэтому, по словам нашего гида,
        именно этот город нужно называть кофейной столицей страны.
        Неоспоримую славу Хмельницкому принес местный рынок, из-за которого город называют столицей торговли.
        Как и на любом рынке, здесь есть свои правила.
        В частности, на "свадебных" рядах свой товар продавцы тщательно оберегают от конкурентов, чтобы те не скопировали модели.
        Поэтому заглянуть в магазинчики разрешается только тем, кто похож на невесту или жениха. Фейс-контроль жесткий.
        В Хмельницком многое говорит о любви. Здесь даже есть "остров любви" — одно из любимых мест отдыха.
        Говорят, в этом городе также самое большое количество в Украине памятников Тарасу Шевченко и собственно Богдану Хмельницкому,
        а в музеях хранятся вещи, которые больше нигде не увидишь.
        Душа города живет в его двориках, на маленьких хозяйствах, которые здесь называют "господами".
        И у черного ореха — древнейшего в городе дерева, настоящего здешнего естественного аккумулятора энергии.
    </p>
</div>
<div id="second_article">
    <h1>Юбилей Обамы: первый темнокожий президент США отпраздновал 60-летие </h1>
    <h2>08.04.2021 20:48</h2>
    <h3>
        Барак Обама моложе обоих своих преемников,
        а действующий президент Соединенных Штатов Джо Байден был у него вице-президентом.
    </h3>
    <p>
        В среду, 4 августа, сорок четвёртому президенту США, лауреату Нобелевской премии Бараку Обаме исполнилось 60 лет.
        О том, чем запомнился американцам первый темнокожий президент и чем он занимается, покинув Белый дом, говорится в сюжете ТСН.19: 30.
        Громкую вечеринку по случаю юбилея Обамы на полтысячи гостей, которую готовили несколько месяцев,
        в последний момент пришлось отменить из-за нового штамма коронавируса "Дельта",
        который распространяется в Соединенных Штатах.
        Поэтому вместо компании с Джорджем Клуни и Стивеном Спилбергом Обаме пришлось ограничиться празднованием в тесном семейном кругу.
        По его собственному утверждению, Барак Обама обязан всему, чего достиг,
        своей жене Мишель. С ней он познакомился в Чикаго, когда пришел стажироваться в компании, где она уже работала.
        Родительской поддержки сын кенийца и белой американки, который родился на Гавайях, не ощущал никогда.
        Со своим отцом будущий президент Соединенных Штатов встретился лишь однажды, когда Бараку было 10 лет.
        О проблемах, которые были в супружеской жизни президентской четы, Мишель Обама рассказала через много лет в своей безумно популярной книге.
        Тогда мир узнал, что паре, которая на экранах выглядит самой счастливой в мире, пришлось работать с психологом, чтобы не расстаться.
        Кстати, Мишель не хотела, чтобы Барак баллотировался в президенты, но все же поддержала его.
        Первый темнокожий президент в истории Соединенных Штатов Барак Обама оставался в Белом доме два срока.
        За эти восемь лет выросли обе его дочери.
        Покинув Белый дом, Обама не только не потерял своей популярности, но и наоборот.
        За его лекции платят бешеные гонорары, его автобиография разошлась тиражом в почти два миллиона за первую же неделю.
        В одной из речей он так и сказал: "Я удивлен, что имею столько денег".
        Два года назад авторитетное издание Financial Times включило Обаму в перечень людей,
        которые определили, как будет выглядеть десятилетия.
    </p>
</div>
<div id="third_article">
    <h1>ВОЗ призывает временно отказаться от бустерных прививок против COVID-19</h1>
    <h2>08.04.2021 19:36</h2>
    <h3>
        По данным ВОЗ, соотношение вакцин к населению в бедных странах составляет 1,5 препарата на 100 человек.
    </h3>
    <p>
        Глава Всемирной организации здравоохранения Тедрос Гебреисус призвал установить мораторий бустерных доз вакцин против коронавируса до конца сентября текущего года.
        Это должно решить вопрос нехватки препаратов в странах с низким уровнем вакцинации.
        Об этом сообщает пресс-служба ВОЗ.
        "ВОЗ призывает к мораторию на бустерные прививки,
        по крайней мере до конца сентября", — заявил Гебреисус во время брифинга.
        По данным ВОЗ, соотношение вакцин к населению в бедных странах составляет 1,5 препарат на 100 человек.
        Также организации напомнила о том, что до конца сентября каждая страна мира должна привить не менее 10% своего населения.
    </p>
</div>

Task23_Low/Views/Commentary/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div id="input_comment">
    <form id="input_fields">
        <p>Name: <input id="username" type="text" placeholder="Enter Username" required /></p>
        <p>Commentary: <textarea id="content" required>Enter Your Commentary Here</textarea></p>
        <input id="submit_button" type="submit" value="Submit" />
    </form>
</div>
<div id="output_comments"></div>

Task23_Low/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Task23_Low/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Task23_Low/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Task23_Low/Views/Questionnaire/Index.cshtml
@{
    ViewBag.Title = "Questionnaire";
}

@helper MultipleAnswerHelper(string[] words, string questionType)
{
        <ol>
            @foreach(string word in words)
            {
                <li>
                    <input name ="mult" type=@questionType id="@word"/>
                    <label for="@word">@word</label>
                </li>
            }
        </ol>
}

<div id="questions">
    <form>
        <div id="question_1">
            <p>What is your Name?</p>
            <input type="text" placeholder="Answer Question" required/>
        </div>
        <div id="question_2">
            <p>What did you like about this site</p>
            @MultipleAnswerHelper(new string[] {"Design", "Speed", "Quality of Information"}, "checkbox")
        </div>
        <div id="question_3">
            <p>Your mood after reading those articles</p>
            @MultipleAnswerHelper(new string[] { "Awfull", "Bad", "Neutrall", "Good", "Awesome"}, "radio")
        </div>
        <input type="submit" value="Submit"/>
    </form>
</div>

Task23_Low/Views/Questionnaire/Result.cshtml
@{
    ViewBag.Title = "Result";
}

<h2>Thank you for your participation</h2>

Task23_Low/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Task23_Low/Views/Shared/_LibraryLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link href="@Url.Content("~/Content/LibraryStyle.css")" rel="stylesheet" type="text/css" />
    <title>Task23_Low</title>
</head>
<body>
    <header id="top">
        <h1>Task23_Low</h1>
    </header>
    <main>
        <div class="right_sidebar">
            <ul>
                <li>@Html.ActionLink("Articles", "Index", "Articles")</li>
                <li>@Html.ActionLink("Commentaries", "Index", "Commentary")</li>
                <li>@Html.ActionLink("Questionnaire", "Index", "Questionnaire")</li>
            </ul>
        </div>
        <div class="main_body">
            @RenderBody()
        </div>
    </main>
    <footer>
        <a href="#top">To the Top</a>
        <p>Ivan Chupryna, Some Email</p>
        <p>Copyright © 2021. Task23_Low.com</p>
    </footer>
</body>
</html>